### ISSUE TITLE
Nice website!

### ISSUE THREAD

**Issue by halaassaly** [WebAhead7/GoogleTasks#14]
We like the design! it is pretty awsome and cool!!
we would recomend you using the break-word feature in css so that if somone writes a long task, the line would break automaticly and will prevent it from overflowing outside the container.

great job overall!! 👍

**Comment by nuwrss** [comment]
we !!! 
thank you for your notice but we don't like it and we don't want to listen to your recommendations .
thank you a lot 😁 

we are working on it .

**Comment by muhammadawwad9** [comment]
Fixed!
