### ISSUE TITLE
Good job but ENTER button doesn't work when press new task

### ISSUE THREAD

**Issue by myassar1211** [WebAhead7/GoogleTasks#5]

**Comment by muhammadawwad9** [comment]
`insertField.addEventListener("keydown",(e)=>{
    if(e.keyCode===13){
        if (insertField.value !== "") {
            let insertedTask = document.querySelector("#add").value;
            let newTask = new New_Task(insertedTask);
           addNewTask(newTask);
        }
        else
            alert("Please type a task to add");
    }
})`

//ISSUE FIXED!
